export const STARTING_BUDGET = Infinity;

export const STAGE_MIN = 0;
export const STAGE_MAX = 6;

export const AVAILABLE_PARTS = [
  {
    id: "data_center_basic",
    name: "Orbital Data Center",
    shortName: "Data Center",
    type: "payload",
    stageAction: "deployPayload",
    cost: 80000,
    payloadRole: "data",
    incomeRate: 7.2,
    researchRate: 0.0056,
    scanRate: 0,
    dryMass: 2.2,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 1.35,
    width: 1.35,
    color: "#a78bfa",
    description: "A starter orbital payload. Stage it in orbit to detach it and generate recurring data-center revenue. After Orbital Telemetry research, it also produces research data."
  },
  {
    id: "satellite_basic",
    name: "Small Satellite",
    shortName: "Satellite",
    type: "payload",
    stageAction: "deployPayload",
    cost: 44000,
    payloadRole: "comms",
    incomeRate: 2.8,
    researchRate: 0.0032,
    scanRate: 0,
    dryMass: 0.8,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.85,
    width: 1.1,
    color: "#c4b5fd",
    description: "A lighter detachable payload. It earns modest recurring revenue when deployed into stable orbit. After Orbital Telemetry research, it generates a small stream of research data."
  },
  {
    id: "nose_cone_basic",
    name: "Basic Nose Cone",
    shortName: "Nose Cone",
    type: "aero",
    cost: 7000,
    dryMass: 0.18,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: -0.45,
    width: 0.85,
    color: "#e2e8f0",
    description: "Reduces atmospheric drag when placed near the top of the rocket."
  },
  {
    id: "command_pod_basic",
    name: "Basic Command Pod",
    shortName: "Command Pod",
    type: "command",
    cost: 20000,
    dryMass: 1.1,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.7,
    width: 1,
    color: "#e5e7eb",
    description: "Required. Gives the rocket a controllable brain."
  },
  {
    id: "parachute_basic",
    name: "Recovery Parachute",
    shortName: "Parachute",
    type: "parachute",
    stageAction: "deployParachute",
    cost: 14000,
    dryMass: 0.25,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.45,
    deployedDragArea: 620,
    safeDeploySpeed: 235,
    width: 1,
    color: "#f9a8d4",
    description: "Stage inside atmosphere to slow descent. It should bring a normal rocket down to a safe landing speed if deployed below its safe speed."
  },
  {
    id: "landing_legs_basic",
    name: "Landing Legs",
    shortName: "Landing Legs",
    type: "legs",
    stageAction: "deployLegs",
    cost: 18000,
    dryMass: 0.45,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.65,
    width: 1.25,
    color: "#94a3b8",
    description: "Stage before touchdown to increase the safe landing speed."
  },
  {
    id: "fuel_tank_small",
    name: "Small Fuel Tank",
    shortName: "Small Tank",
    type: "fuel",
    cost: 13000,
    dryMass: 0.65,
    fuelCapacity: 281.25,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.65,
    width: 1,
    color: "#38bdf8",
    description: "Light tank with 25% more fuel capacity. Good for upper stages and small orbital launches."
  },
  {
    id: "fuel_tank_medium",
    name: "Medium Fuel Tank",
    shortName: "Med Tank",
    type: "fuel",
    cost: 24000,
    dryMass: 1.05,
    fuelCapacity: 437.5,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.85,
    width: 1.1,
    color: "#0ea5e9",
    description: "Balanced fuel storage with 25% more capacity for most early rockets."
  },
  {
    id: "fuel_tank_composite",
    name: "Composite Fuel Tank",
    shortName: "Composite Tank",
    type: "fuel",
    requiresResearch: "composite_tanks",
    cost: 52000,
    dryMass: 0.92,
    fuelCapacity: 625,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.9,
    width: 1.12,
    color: "#67e8f9",
    description: "Unlocked through Composite Tanks research. Holds significantly more fuel while staying lighter than a stack of smaller tanks."
  },
  {
    id: "decoupler_basic",
    name: "Basic Decoupler",
    shortName: "Decoupler",
    type: "decoupler",
    stageAction: "decoupleBelow",
    cost: 11000,
    dryMass: 0.22,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.35,
    width: 1.05,
    color: "#facc15",
    description: "Stage to drop this part and everything below it. Great for shedding empty tanks and engines."
  },
  {
    id: "data_center_efficient",
    name: "Efficient Data Center",
    shortName: "Efficient DC",
    type: "payload",
    stageAction: "deployPayload",
    requiresResearch: "cloud_processing",
    cost: 160000,
    payloadRole: "data",
    incomeRate: 15.2,
    researchRate: 0.011,
    scanRate: 0,
    dryMass: 2.8,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 1.45,
    width: 1.42,
    color: "#8b5cf6",
    description: "Unlocked through Cloud Processing research. A better orbital data center with stronger income and research output."
  },
  {
    id: "exploration_satellite_basic",
    name: "Exploration Satellite",
    shortName: "Explorer Sat",
    type: "payload",
    stageAction: "deployPayload",
    requiresResearch: "orbital_surveying",
    cost: 180000,
    payloadRole: "exploration",
    incomeRate: 1.6,
    researchRate: 0.018,
    scanRate: 0.18,
    dryMass: 1.15,
    fuelCapacity: 0,
    thrust: 0,
    fuelUse: 0,
    dragArea: 0.95,
    width: 1.18,
    color: "#22d3ee",
    description: "Unlocked through Orbital Surveying research. This is the first planet-discovery payload and generates Scan/sec for unknown-signal discovery milestones."
  },
  {
    id: "engine_vacuum",
    name: "Vacuum Engine",
    shortName: "Vac Engine",
    type: "engine",
    cost: 62000,
    dryMass: 1.05,
    fuelCapacity: 0,
    thrust: 148.5,
    fuelUse: 6.1,
    dragArea: 0.7,
    width: 1,
    color: "#fdba74",
    description: "Balanced thrust, better fuel use. Best after the lower stage separates."
  },
  {
    id: "engine_basic",
    name: "Basic Engine",
    shortName: "Basic Engine",
    type: "engine",
    cost: 50000,
    dryMass: 1.35,
    fuelCapacity: 0,
    thrust: 198,
    fuelUse: 9.2,
    dragArea: 0.8,
    width: 1.05,
    color: "#f97316",
    description: "Reliable starter engine with 20% more thrust for larger-world launches."
  },
  {
    id: "engine_heavy",
    name: "Heavy Engine",
    shortName: "Heavy Engine",
    type: "engine",
    cost: 84000,
    dryMass: 2.1,
    fuelCapacity: 0,
    thrust: 324,
    fuelUse: 15.4,
    dragArea: 1.05,
    width: 1.25,
    color: "#fb923c",
    description: "More thrust for heavy payloads, but burns fuel quickly."
  },
  {
    id: "engine_skyburner",
    name: "Skyburner Engine",
    shortName: "Skyburner",
    type: "engine",
    requiresResearch: "vacuum_engine_design",
    cost: 98000,
    dryMass: 1.18,
    fuelCapacity: 0,
    thrust: 186,
    fuelUse: 6.7,
    dragArea: 0.72,
    width: 1.04,
    color: "#f59e0b",
    description: "Unlocked through Vacuum Engine Design research. Efficient upper-stage thrust for cleaner circularization burns."
  },
  {
    id: "engine_titan",
    name: "Titan Engine",
    shortName: "Titan",
    type: "engine",
    requiresResearch: "heavy_lift_engineering",
    cost: 165000,
    dryMass: 2.45,
    fuelCapacity: 0,
    thrust: 450,
    fuelUse: 16.6,
    dragArea: 1.15,
    width: 1.34,
    color: "#ea580c",
    description: "Unlocked through Heavy Lift Engineering research. A premium high-thrust engine for large payloads and future interplanetary launchers."
  }
];

// stage 0 = passive/active during flight. Stage 1+ is activated by the Stage button.
export const STARTING_STACK = [
  { id: "nose_cone_basic", stage: 0 },
  { id: "data_center_basic", stage: 2 },
  { id: "command_pod_basic", stage: 0 },
  { id: "parachute_basic", stage: 3 },
  { id: "landing_legs_basic", stage: 3 },
  { id: "fuel_tank_small", stage: 0 },
  { id: "engine_vacuum", stage: 0 },
  { id: "decoupler_basic", stage: 1 },
  { id: "fuel_tank_medium", stage: 0 },
  { id: "fuel_tank_medium", stage: 0 },
  { id: "engine_basic", stage: 0 }
];

export function getPartById(id) {
  const part = AVAILABLE_PARTS.find((candidate) => candidate.id === id);
  if (!part) throw new Error(`Unknown rocket part: ${id}`);
  return part;
}
